// @generated by scripts/build-compute-wasm.ps1 â€” do not edit by hand.
//
// The pinned WebAssembly coprocessor artifact. WASM_SHA256 is recomputed from
// the embedded bytes by \	ests::embedded_artifact_matches_pinned_digest\, so a
// swapped or rebuilt artifact that was not re-pinned fails a test instead of
// silently changing what the model sees.

pub const WASM_ARTIFACT: &[u8] = include_bytes!("../assets/compute_bank_v1.wasm");
pub const WASM_SHA256: &str = "363b81d6a5aeb6b48df3f578d9fa5ec52b255e55ba4dd681f05861719709f140";
pub const WASM_ARTIFACT_BYTES: usize = 1588526;
/// Git revision the artifact was built from (provenance only).
pub const WASM_BUILT_FROM: &str = "fe3fdb727cb3dcfb4670619bc809e11fb568b7c8";
