// @generated by scripts/build-compute-wasm.ps1 â€” do not edit by hand.
//
// The pinned WebAssembly coprocessor artifact. WASM_SHA256 is recomputed from
// the embedded bytes by \	ests::embedded_artifact_matches_pinned_digest\, so a
// swapped or rebuilt artifact that was not re-pinned fails a test instead of
// silently changing what the model sees.

pub const WASM_ARTIFACT: &[u8] = include_bytes!("../assets/compute_bank_v1.wasm");
pub const WASM_SHA256: &str = "f96b5e555c9cbf7203d62244e0dca825b10a63411f94107971798003114ebeab";
pub const WASM_ARTIFACT_BYTES: usize = 1577622;
/// Git revision the artifact was built from (provenance only).
pub const WASM_BUILT_FROM: &str = "a8aef66899c2cca9aaf79a897656d09246b17903";
