//! `recur64 search-gain` — prior vs visit-target divergence of a replay.
//!
//! Re-evaluates every replay position with the network that generated it and
//! reports KL(target || prior), argmax change, and entropy / top-1 for both.
//! Refuses a checkpoint whose model_id differs from the replay's generating
//! model, since the "prior" would then be a different network's policy.

use std::path::PathBuf;

use burn::prelude::*;
use burn::tensor::backend::AutodiffBackend;
use clap::Args;

use recur64_runtime::replay::ReplayReader;
use recur64_runtime::search_gain::search_gain;
use recur64_runtime::{BatchedModel, RunConfig, model_io};

type CpuTrain = burn::backend::Autodiff<burn::backend::Flex>;

#[derive(Args, Debug)]
pub struct SearchGainArgs {
    #[arg(long)]
    pub config: PathBuf,
    /// Checkpoint of the network that generated the replay.
    #[arg(long)]
    pub checkpoint: PathBuf,
    #[arg(long)]
    pub replay: PathBuf,
    #[arg(long)]
    pub output: PathBuf,
    #[arg(long, default_value_t = 64)]
    pub batch: usize,
}

fn run_impl<B: AutodiffBackend>(cfg: &RunConfig, args: &SearchGainArgs) -> anyhow::Result<()> {
    let reader = ReplayReader::open(&args.replay)?;
    let replay_model_id = reader.manifest().header.model_id.clone();
    let checkpoint_model_id = std::fs::read(args.checkpoint.join("meta.json"))
        .ok()
        .and_then(|b| serde_json::from_slice::<serde_json::Value>(&b).ok())
        .and_then(|v| {
            v.get("model_id")
                .and_then(|m| m.as_str())
                .map(str::to_owned)
        })
        .ok_or_else(|| anyhow::anyhow!("checkpoint has no model_id in meta.json"))?;
    anyhow::ensure!(
        replay_model_id == checkpoint_model_id,
        "replay was generated by {replay_model_id}, not checkpoint {checkpoint_model_id}"
    );
    let games = reader.read_all_games()?;
    let search = games.first().map(|g| g.search.clone());
    let device: Device<B::InnerBackend> = Default::default();
    let model = model_io::load::<B::InnerBackend>(&args.checkpoint, &cfg.model, &device)?;
    let batched = BatchedModel::new(model, cfg.recurrence, device);
    let gain = search_gain(&batched, &games, args.batch)?;
    let report = serde_json::json!({
        "replay": args.replay,
        "games": games.len(),
        "search": search,
        "model_id": checkpoint_model_id,
        "gain": gain,
    });
    std::fs::create_dir_all(&args.output)?;
    std::fs::write(
        args.output.join("search-gain.json"),
        serde_json::to_vec_pretty(&report)?,
    )?;
    println!("{}", serde_json::to_string_pretty(&report)?);
    Ok(())
}

pub fn run(args: SearchGainArgs) -> anyhow::Result<()> {
    let cfg = RunConfig::from_toml_str(&std::fs::read_to_string(&args.config)?)?;
    cfg.ensure_supported()?;
    match cfg.device.as_str() {
        "cpu" => run_impl::<CpuTrain>(&cfg, &args),
        "cuda" => {
            #[cfg(feature = "cuda")]
            {
                run_impl::<burn::backend::Autodiff<burn::backend::Cuda>>(&cfg, &args)
            }
            #[cfg(not(feature = "cuda"))]
            {
                anyhow::bail!("CUDA support is not compiled; rebuild with --features cuda")
            }
        }
        other => anyhow::bail!("unknown device '{other}'"),
    }
}
