//! `recur64 search-gain` — network-to-target divergence of a replay.
//!
//! Re-evaluates every replay position with the network that generated it and
//! reports KL(visit target || raw network policy), argmax change, and entropy
//! / top-1 for both, plus value/WDL and repetition indicators. Under root
//! Dirichlet noise (D41) this includes exploration noise as well as search
//! movement; the exact split is in self-play's `root_search` diagnostics.
//! Refuses a checkpoint whose model_id differs from the replay's generating
//! model (from `replay-identity.json` when present, else the manifest header,
//! reported as a legacy/unverified search contract).

use std::path::PathBuf;

use burn::prelude::*;
use burn::tensor::backend::AutodiffBackend;
use clap::Args;

use recur64_runtime::replay::ReplayReader;
use recur64_runtime::search_gain::search_gain;
use recur64_runtime::{BatchedModel, RunConfig, model_io};

type CpuTrain = burn::backend::Autodiff<burn::backend::Flex>;

#[derive(Args, Debug)]
pub struct SearchGainArgs {
    #[arg(long)]
    pub config: PathBuf,
    /// Checkpoint of the network that generated the replay.
    #[arg(long)]
    pub checkpoint: PathBuf,
    #[arg(long)]
    pub replay: PathBuf,
    #[arg(long)]
    pub output: PathBuf,
    #[arg(long, default_value_t = 64)]
    pub batch: usize,
    /// Restrict to replay games with id in [first_game_id, first_game_id + games)
    /// (e.g. one pilot cycle, generated by one snapshot).
    #[arg(long)]
    pub first_game_id: Option<u64>,
    #[arg(long)]
    pub games: Option<u64>,
}

fn run_impl<B: AutodiffBackend>(cfg: &RunConfig, args: &SearchGainArgs) -> anyhow::Result<()> {
    let reader = ReplayReader::open(&args.replay)?;
    let replay_model_id = reader.manifest().header.model_id.clone();
    let lo = args.first_game_id.unwrap_or(0);
    let hi = args.games.map_or(u64::MAX, |g| lo.saturating_add(g));
    let ranged = args.first_game_id.is_some() || args.games.is_some();
    let checkpoint_model_id = std::fs::read(args.checkpoint.join("meta.json"))
        .ok()
        .and_then(|b| serde_json::from_slice::<serde_json::Value>(&b).ok())
        .and_then(|v| {
            v.get("model_id")
                .and_then(|m| m.as_str())
                .map(str::to_owned)
        })
        .ok_or_else(|| anyhow::anyhow!("checkpoint has no model_id in meta.json"))?;
    // With a game range, the sidecar entries covering it decide the
    // generating model; the manifest header only names the first writer.
    anyhow::ensure!(
        ranged || replay_model_id == checkpoint_model_id,
        "replay was generated by {replay_model_id}, not checkpoint {checkpoint_model_id}"
    );
    let identity = recur64_runtime::replay_identity::read(&args.replay)?;
    let search_contract = match &identity {
        Some(id) => {
            let covering: Vec<_> = id
                .entries
                .iter()
                .filter(|e| e.first_game_id < hi && e.first_game_id + e.games > lo)
                .collect();
            anyhow::ensure!(
                !covering.is_empty(),
                "no replay-identity entry covers the requested games"
            );
            let foreign: Vec<&str> = covering
                .iter()
                .filter(|e| e.model_id != checkpoint_model_id)
                .map(|e| e.model_id.as_str())
                .collect();
            anyhow::ensure!(
                foreign.is_empty(),
                "replay-identity names generating models {foreign:?}, not checkpoint {checkpoint_model_id}"
            );
            "verified (replay-identity.json)"
        }
        None => {
            anyhow::ensure!(
                !ranged,
                "a game range needs replay-identity.json to name the generating model"
            );
            "legacy/unverified search contract (no replay-identity.json)"
        }
    };
    let games: Vec<_> = reader
        .read_all_games()?
        .into_iter()
        .filter(|g| g.game_id >= lo && g.game_id < hi)
        .collect();
    anyhow::ensure!(!games.is_empty(), "no replay games in the requested range");
    let search = games.first().map(|g| g.search.clone());
    let device: Device<B::InnerBackend> = Default::default();
    let model = model_io::load::<B::InnerBackend>(&args.checkpoint, &cfg.model, &device)?;
    let batched = BatchedModel::new(model, cfg.recurrence, device);
    let gain = search_gain(&batched, &games, args.batch)?;
    let report = serde_json::json!({
        "metric": "network_to_target_divergence",
        "semantics": "visit target vs RAW network policy; includes root exploration noise (D41) and tree-search movement; see self-play root_search for the exact split",
        "search_contract": search_contract,
        "replay_identity": identity,
        "replay": args.replay,
        "game_range": {"first_game_id": lo, "end_exclusive": (hi != u64::MAX).then_some(hi)},
        "games": games.len(),
        "search": search,
        "model_id": checkpoint_model_id,
        "gain": gain,
    });
    std::fs::create_dir_all(&args.output)?;
    std::fs::write(
        args.output.join("search-gain.json"),
        serde_json::to_vec_pretty(&report)?,
    )?;
    println!("{}", serde_json::to_string_pretty(&report)?);
    Ok(())
}

pub fn run(args: SearchGainArgs) -> anyhow::Result<()> {
    let cfg = RunConfig::from_toml_str(&std::fs::read_to_string(&args.config)?)?;
    cfg.ensure_supported()?;
    match cfg.device.as_str() {
        "cpu" => run_impl::<CpuTrain>(&cfg, &args),
        "cuda" => {
            #[cfg(feature = "cuda")]
            {
                run_impl::<burn::backend::Autodiff<burn::backend::Cuda>>(&cfg, &args)
            }
            #[cfg(not(feature = "cuda"))]
            {
                anyhow::bail!("CUDA support is not compiled; rebuild with --features cuda")
            }
        }
        other => anyhow::bail!("unknown device '{other}'"),
    }
}
