[package]
name = "recur64-eval"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[features]
default = ["cpu"]
cpu = ["recur64-runtime/cpu"]
cuda = ["recur64-runtime/cuda"]

[dependencies]
recur64-core = { path = "../recur64-core" }
recur64-search = { path = "../recur64-search" }
recur64-runtime = { path = "../recur64-runtime", default-features = false }
serde = { workspace = true }

[dev-dependencies]
burn = { workspace = true, features = ["std", "flex"] }
recur64-model = { path = "../recur64-model", default-features = false }
