# Build the WebAssembly coprocessor artifact reproducibly.
#
# Run from the repository root:
#     pwsh -File scripts/build-compute-wasm.ps1
#
# Deliberately a standalone script rather than a `build.rs`: a build script that
# shells out to cargo would re-enter the build (the AGENTS.md prohibition), and
# it would make the artifact depend on the machine's cargo state. This script
# builds once, copies the `.wasm` into `crates/recur64-compute/assets/`, and
# writes the pinned SHA-256 into `crates/recur64-compute/src/artifact.rs`, which
# the `WasmV1` provider embeds. Re-running it with unchanged sources and
# unchanged toolchain must produce an identical digest.

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$target = "wasm32-unknown-unknown"
$profile = "wasm-release"
$outDir = Join-Path $root "crates/recur64-compute/assets"
$artifact = Join-Path $outDir "compute_bank_v1.wasm"
$generated = Join-Path $root "crates/recur64-compute/src/artifact.rs"

Write-Host "== rustup target =="
$installed = (rustup target list --installed) -split "`n" | ForEach-Object { $_.Trim() }
if ($installed -notcontains $target) {
    throw "target $target is not installed; run: rustup target add $target"
}

Write-Host "== building recur64-coproc-guest for $target ($profile) =="
Push-Location $root
try {
    cargo build --profile $profile --target $target -p recur64-coproc-guest
} finally {
    Pop-Location
}

$built = Join-Path $root "target/$target/$profile/recur64_coproc_guest.wasm"
if (-not (Test-Path $built)) {
    throw "expected artifact not found: $built"
}

New-Item -ItemType Directory -Force -Path $outDir | Out-Null
Copy-Item -Force $built $artifact

$bytes = [System.IO.File]::ReadAllBytes($artifact)
$sha = [System.Security.Cryptography.SHA256]::Create()
$digest = ($sha.ComputeHash($bytes) | ForEach-Object { $_.ToString("x2") }) -join ""

Write-Host "== artifact =="
Write-Host "  path   : crates/recur64-compute/assets/compute_bank_v1.wasm"
Write-Host ("  bytes  : {0}" -f $bytes.Length)
Write-Host "  sha256 : $digest"

$revision = (& git -C $root rev-parse HEAD).Trim()
$content = @"
// @generated by scripts/build-compute-wasm.ps1 — do not edit by hand.
//
// The pinned WebAssembly coprocessor artifact. `WASM_SHA256` is recomputed from
// the embedded bytes by \`tests::embedded_artifact_matches_pinned_digest\`, so a
// swapped or rebuilt artifact that was not re-pinned fails a test instead of
// silently changing what the model sees.

pub const WASM_ARTIFACT: &[u8] = include_bytes!("../assets/compute_bank_v1.wasm");
pub const WASM_SHA256: &str = "$digest";
pub const WASM_ARTIFACT_BYTES: usize = $($bytes.Length);
/// Git revision the artifact was built from (provenance only).
pub const WASM_BUILT_FROM: &str = "$revision";
"@
Set-Content -Path $generated -Value $content -Encoding utf8 -NoNewline
Write-Host "  wrote  : crates/recur64-compute/src/artifact.rs"
