# Build the WebAssembly coprocessor artifact reproducibly.
#
# Run from the repository root:
#     pwsh -File scripts/build-compute-wasm.ps1
#
# Deliberately a standalone script rather than a `build.rs`: a build script that
# shells out to cargo would re-enter the build (the AGENTS.md prohibition), and
# it would make the artifact depend on the machine's cargo state. This script
# builds once, copies the `.wasm` into `crates/recur64-compute/assets/`, and
# writes the pinned SHA-256 into `crates/recur64-compute/src/artifact.rs`, which
# the `WasmV1` provider embeds. Re-running it with unchanged sources and
# unchanged toolchain must produce an identical digest.

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$target = "wasm32-unknown-unknown"
$profile = "wasm-release"
$outDir = Join-Path $root "crates/recur64-compute/assets"
$artifact = Join-Path $outDir "compute_bank_v1.wasm"
$generated = Join-Path $root "crates/recur64-compute/src/artifact.rs"

Write-Host "== rustup target =="
$installed = (rustup target list --installed) -split "`n" | ForEach-Object { $_.Trim() }
if ($installed -notcontains $target) {
    throw "target $target is not installed; run: rustup target add $target"
}

Write-Host "== building recur64-coproc-guest for $target ($profile) =="
Push-Location $root
try {
    cargo build --profile $profile --target $target -p recur64-coproc-guest
} finally {
    Pop-Location
}

$built = Join-Path $root "target/$target/$profile/recur64_coproc_guest.wasm"
if (-not (Test-Path $built)) {
    throw "expected artifact not found: $built"
}

New-Item -ItemType Directory -Force -Path $outDir | Out-Null
Copy-Item -Force $built $artifact

$bytes = [System.IO.File]::ReadAllBytes($artifact)
$sha = [System.Security.Cryptography.SHA256]::Create()
$digest = ($sha.ComputeHash($bytes) | ForEach-Object { $_.ToString("x2") }) -join ""

Write-Host "== artifact =="
Write-Host "  path   : crates/recur64-compute/assets/compute_bank_v1.wasm"
Write-Host ("  bytes  : {0}" -f $bytes.Length)
Write-Host "  sha256 : $digest"

# ---- provenance ---------------------------------------------------------------
# The source digest covers exactly the files that determine the artifact:
#   crates/recur64-coproc/src/*.rs, crates/recur64-coproc-guest/src/lib.rs and the
#   two Cargo.toml files. Line endings are normalised (CRLF -> LF) so the digest is
#   identical on any checkout. Algorithm (mirrored by the Rust test
#   `artifact_source_digest_matches_the_sources`): SHA-256 over, for each file in
#   ordinal path order, UTF-8(relative path with '/') + 0x00 + normalised bytes + 0x00.
$sourceFiles = @()
Get-ChildItem (Join-Path $root "crates/recur64-coproc/src") -Filter *.rs | ForEach-Object {
    $sourceFiles += "crates/recur64-coproc/src/$($_.Name)"
}
$sourceFiles += "crates/recur64-coproc-guest/src/lib.rs"
$sourceFiles += "crates/recur64-coproc/Cargo.toml"
$sourceFiles += "crates/recur64-coproc-guest/Cargo.toml"
[Array]::Sort($sourceFiles, [System.StringComparer]::Ordinal)

$ms = New-Object System.IO.MemoryStream
foreach ($rel in $sourceFiles) {
    $nameBytes = [System.Text.Encoding]::UTF8.GetBytes($rel)
    $ms.Write($nameBytes, 0, $nameBytes.Length)
    $ms.WriteByte(0)
    $raw = [System.IO.File]::ReadAllBytes((Join-Path $root $rel))
    for ($i = 0; $i -lt $raw.Length; $i++) {
        if ($raw[$i] -eq 13 -and ($i + 1) -lt $raw.Length -and $raw[$i + 1] -eq 10) { continue }
        $ms.WriteByte($raw[$i])
    }
    $ms.WriteByte(0)
}
$srcSha = [System.Security.Cryptography.SHA256]::Create()
$sourceDigest = ($srcSha.ComputeHash($ms.ToArray()) | ForEach-Object { $_.ToString("x2") }) -join ""

# Honest revision label: the artifact was built from HEAD only if the source files
# are committed and unmodified; otherwise say so.
$revision = (& git -C $root rev-parse HEAD).Trim()
$dirty = (& git -C $root status --porcelain -- $sourceFiles)
if ($dirty) { $revisionLabel = "$revision+uncommitted-sources" } else { $revisionLabel = $revision }
Write-Host "  source : $sourceDigest ($($sourceFiles.Count) files)"
Write-Host "  built  : $revisionLabel"

$content = @"
// @generated by scripts/build-compute-wasm.ps1 - do not edit by hand.
//
// The pinned WebAssembly coprocessor artifact. WASM_SHA256 is recomputed from the
// embedded bytes by tests::embedded_artifact_matches_pinned_digest, and
// WASM_SOURCE_DIGEST is recomputed from the coprocessor sources by
// tests::artifact_source_digest_matches_the_sources, so a swapped artifact OR a
// source change that was not followed by a rebuild fails a test instead of silently
// changing what the model sees.

pub const WASM_ARTIFACT: &[u8] = include_bytes!("../assets/compute_bank_v1.wasm");
pub const WASM_SHA256: &str = "$digest";
pub const WASM_ARTIFACT_BYTES: usize = $($bytes.Length);
/// SHA-256 of the sources the artifact was built from (see the build script for the algorithm).
pub const WASM_SOURCE_DIGEST: &str = "$sourceDigest";
/// Git HEAD at build time. A "+uncommitted-sources" suffix means the sources were not
/// yet committed, so this revision does NOT contain the exact sources; rely on
/// WASM_SOURCE_DIGEST for reproducibility. Provenance only.
pub const WASM_BUILT_FROM: &str = "$revisionLabel";
"@
[System.IO.File]::WriteAllText($generated, $content, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "  wrote  : crates/recur64-compute/src/artifact.rs"
